{%set build = 0 %}

package:
  name: shutilwhich
  version: !!str 1.1.0

about:
  home: https://github.com/mbr/shutilwhich
  license: PSF License
  summary: "shutil.which for those not using Python 3.3 yet."

source:
  fn: shutilwhich-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/s/shutilwhich/shutilwhich-1.1.0.tar.gz
  md5: 915947c5cdae7afd748ac715ee547adb

requirements:
  build:
    - python
    - setuptools

  run:
    - python

build:
  number: {{build}}
  script: python setup.py install
